# run: conda env create --file environment.yml
name: othpcuqtraining
dependencies:
- python>=3.5
- numpy>=1.16.*
- matplotlib>=2.*
- scipy>=1.*
- openturns==1.18
- otwrapy
- jupyterlab
- nbconvert
- black==19.10b0
- pre-commit
- flake8
- tqdm
- pip
- pandas
- pip:
  - black-nb

